# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'BadTemper'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view_adapter nice_view_gem","temper_right nice_view_adapter nice_view_gem"]'
      nav: '["invertedT"]'
      layers: '["flip"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y","CONFIG_ZMK_DISPLAY=y","CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y","CONFIG_NICE_VIEW_GEM_ANIMATION=n"]'
      modules: '["M165437/nice-view-gem/main"]'
