# Copyright 2022 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'BadTemper'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["nice_nano_v2"]'
      shield: '["temper_left nice_view_adapter nice_view_gem","temper_right nice_view_adapter nice_view_gem"]'
      nav: '["invertedT"]'
      layers: '["flip"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_DISPLAY=y\nCONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y\nCONFIG_NICE_VIEW_GEM_ANIMATION=n\nCONFIG_ZMK_MOUSE=y"]'
      branches: '["petejohanson/zmk/feat/pointers-move-scroll"]'
      modules: '["M165437/nice-view-gem/main"]'
